ALTER TABLE indexed_documents
    ADD COLUMN external_access VARCHAR;

ALTER TABLE ingestion_errors
    ADD COLUMN entity_id VARCHAR(2048);
ALTER TABLE ingestion_errors
    ADD COLUMN failed_time_range_start TIMESTAMP WITH TIME ZONE;
ALTER TABLE ingestion_errors
    ADD COLUMN failed_time_range_end TIMESTAMP WITH TIME ZONE;

CREATE TABLE permission_sync_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cc_pair_id BIGINT NOT NULL REFERENCES connector_credential_pairs(id) ON DELETE CASCADE,
    status VARCHAR(32) NOT NULL DEFAULT 'NOT_STARTED',
    error_msg TEXT,
    time_started TIMESTAMP WITH TIME ZONE,
    time_finished TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    active_marker SMALLINT DEFAULT 1,
    CONSTRAINT uq_permission_sync_attempt_active UNIQUE (cc_pair_id, active_marker)
);

ALTER TABLE connector_credential_pairs
    ADD COLUMN last_pruned_at TIMESTAMP WITH TIME ZONE;
